fos_elastica:
  clients:
    default: { host: elasticsearch , port: 9200 }
  #serializer: ~
  indexes:
    app:
      index_name: product_name
      #client: default
      types:
        Product:
          persistence:
          #            # the driver can be orm, mongodb or phpcr
            driver: orm
            model: App\Entity\Product
            provider: ~
            repository: App\SearchRepository\ProductRepository
          properties:
            name:
              #analyzer: keyword_analyzer
              #search_analyzer: keyword_analyzer
              type: text
            description:
              type: text
          serializer:
            groups: [productList]
            #description: text
