
fos_elastica:
  clients:
    default: { host: '%env(resolve:ELASTICSEARCH_HOST)%', port: '%env(resolve:ELASTICSEARCH_PORT)%' }
  indexes:
    obtao_blog:
      client: default
      types:
        article:
          mappings:
            id:
              type: integer
            createdAt :
              type : date
            publishedAt :
              type : date
            published :
              type : boolean
            title : ~
            content : ~
          persistence:
            driver: orm
            model: App\Entity\Product
            finder: ~
            provider: ~
            listener: ~